<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>FunctionalTests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>2e5f5db6-0e31-45dd-a3be-5478d1651b87</testSuiteGuid>
   <testCaseLink>
      <guid>c3235b81-21e8-44f6-ba34-7b0280c7e686</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Category/Add_Edit_Delete_Category</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0b5ee80b-0a15-4437-9c21-6cbe6860ef76</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/RawData/categoryData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0b5ee80b-0a15-4437-9c21-6cbe6860ef76</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>17517cd8-08a9-4ce6-86dd-3cd94dd21ee3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a21aebd-06ea-4432-b83f-dabc209f221f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Task/Cancel_Adding_New_Task</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dc0f7937-eda8-4aee-bd8e-0a4061c71ac1</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/taskData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dc0f7937-eda8-4aee-bd8e-0a4061c71ac1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>taskTitle</value>
         <variableId>fa3eaf9b-1cc6-4efd-bbd9-a1715cb2c371</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dc0f7937-eda8-4aee-bd8e-0a4061c71ac1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>activity</value>
         <variableId>48c22924-0845-47d2-95ae-00fc0db628fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e642a4a-2cdc-4ee7-8f9b-d562ab5b2a6d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Task/Add_New_Task</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>92db5268-51ef-44aa-bd31-6379481f272a</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/taskData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>92db5268-51ef-44aa-bd31-6379481f272a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>taskTitle</value>
         <variableId>d51b97aa-5497-4798-a7b1-9ba05c880f96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>92db5268-51ef-44aa-bd31-6379481f272a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>activity</value>
         <variableId>873e35ac-d8a6-41fe-9924-ca9a470a0111</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>92db5268-51ef-44aa-bd31-6379481f272a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>4c0ed28a-5cf7-490d-944a-37fd503d1b8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d915324-1ac7-4700-be80-452ef5f2d205</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa6fee22-e804-4e0f-b9af-0e2ce06ea9b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2b1f88cf-78d4-4fa6-aa68-193cd6155fcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Task/Edit_Task</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7df2e5bf-d082-4257-a530-16cc33c479bc</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/taskData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7df2e5bf-d082-4257-a530-16cc33c479bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>taskTitle</value>
         <variableId>397df972-aa76-458d-9320-d85af017eb1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7df2e5bf-d082-4257-a530-16cc33c479bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>activity</value>
         <variableId>da91d660-c0ed-418e-bf11-3135c2848489</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7df2e5bf-d082-4257-a530-16cc33c479bc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>category</value>
         <variableId>c7dc1d74-c4ce-4f3b-8585-bc3fece792f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3e115d3-0af9-4597-9705-1167dd66ead2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>057903cc-37aa-4ee4-9177-7de20012ebae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>924d929a-aa78-4e31-bca8-948efb7f9467</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Task/Copy_Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0019d14c-12e0-4bcf-a789-3026868925f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Task/Delete_Task</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
